spring.application.name=notification-service
server.port=9003
spring.kafka.consumer.group-id=ion

# Logging configuration (Set level to DEBUG for verbose output)
logging.level.root=INFO
logging.level.com.yourcompany.app=DEBUG